### ISSUE TITLE
CORS request error 

### ISSUE THREAD

**Issue by demonhue** [jikan-me/jikan-rest#201]
I am having trouble searching for anime, it says "Access to XMLHttpRequest at 'https://api.jikan.moe/v4/anime?q=boruto&limit=10&order_by=title&sort=asc' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by irfan-dahir** [comment]
Hi, I'm not sure what's causing this for you, and neither could I reproduce it. The CORS headers are present on that request.

How are you making this request?

**Comment by demonhue** [comment]
### How I am making request:
`const { data: d } = await axios.get('https://api.jikan.moe/v4/anime/'+id);`

### What it says in the console:
`Access to XMLHttpRequest at 'https://api.jikan.moe/v4/anime/36951' from origin 'http://localhost:3000' has been blocked; by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

### The fix I've been using:
`const { data: d } = await axios.get('https://some-name-i-wont-mention.herokuapp.com/https://api.jikan.moe/v4/anime/'+id);`
[from here](https://github.com/Rob--W/cors-anywhere/)

###The problem with the fix:
the requests are somewhat slow.
So, I would appreciate your help.
Maybe I am missing some header.

**Comment by demonhue** [comment]
### It is fixed now
instead of making calls to Jikan from the frontend, I made them from the backend, and it worked!

maybe because I was prefixing every call from frontend with `http://localhost:5000/`
i.e., I had `"proxy": "http://localhost:5000/"` in my package.json on the frontend side.
But maybe it had nothing to do with the problem.
.It doesn't matter; it works perfectly fine now.

**Comment by irfan-dahir** [comment]
Glad you resolved it. I'll go ahead and close the issue then.

But FYI, I tried out axios and fetch. They both seem to work on my end (from the frontend). So I'm still not sure what the issue for you is.

Axios: https://jsfiddle.net/ec7d8omh/
Fetch: https://jsfiddle.net/3yktdna0/

Perhaps passing `crossdomain: true` in your axios configs might fix it. e.g `axios.get(url, { crossdomain: true })`. 

Additionally, someone else had a CORS problem and mentioned it over on our discord. They said they fixed it by switching over to Fetch.
Link to discussion: https://discord.com/channels/460491088004907029/461199124205797439/933295304399290391
