### ISSUE TITLE
Impossible to get next pages of the user friends list

### ISSUE THREAD

**Issue by cyber-sec0** [jikan-me/jikan-rest#224]
The API always return has_next_page as false no matter the amount of friends the user has
https://myanimelist.net/profile/abystoma2/friends?p=2

Also the documentation for that https://docs.api.jikan.moe/#operation/getUserFriends does not explain at all how to get the next pages, but in the Jikan API v3 all was need was to add a /1 /2 and so on in the end of the query to get the next pages.

I've tried doing that and also https://api.jikan.moe/v4/users/UserName/friends?p=2 and so on and it didn't work either.

On any of these 2 pagination systems I've tried I always get the same 100 usernames if I query page 1 and 2 very fast.

Please fix this bug!

**Comment by cyber-sec0** [comment]
Is adding a /1 /2 and so on in the end of the query correct to get the next pages?

**Comment by irfan-dahir** [comment]
@cyber-sec0 No, in v4 pagination is dealt with `?page=1`. There was a bug which I've fixed for user friends. I'll push the fix to the API server soon.

**Comment by cyber-sec0** [comment]
@irfan-dahir [irfan-dahir](https://github.com/irfan-dahir)
Thanks, I will wait for that because for now it still seems like this bug wasn't fixed.

**Comment by irfan-dahir** [comment]
Resolved.
https://api.jikan.moe/v4/users/abystoma2/friends?page=1
https://api.jikan.moe/v4/users/abystoma2/friends?page=2

**Comment by cyber-sec0** [comment]
@[irfan-dahir]

Now the amount of pages are infinite and data.length is always 100 even if the page 99 has 0 friends on it.

https://api.jikan.moe/v4/users/abystoma2/friends?page=99

**Comment by cyber-sec0** [comment]
Any updates after almost a year?

**Comment by pushrbx** [comment]
Nothing yet. I've looked into this, and the problem is in the Jikan lib, it doesn't parse the page properly. Will fix sometime.

**Comment by irfan-dahir** [comment]
I'll look into this
