### ISSUE TITLE
🐛 Searching for "Ninjala" returns results for "Ninja"

### ISSUE THREAD

**Issue by Prid13** [jikan-me/jikan-rest#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Searching for "Ninjala" and "Ninja" returns the same results: `https://api.jikan.moe/v4/anime?q=ninjala&sfw`

Naruto and other ninja animes show up:

![image](https://github.com/jikan-me/jikan-rest/assets/27897747/cc0b5613-09e9-45eb-a149-c3aa82601060)

### Expected Behavior

The [Ninjala anime](https://myanimelist.net/anime/50418/Ninjala_TV) is supposed to be returned, along with its related series (ONA episodes)

### Anything else?

If I try searching for "Ninjala**la**", the correct anime shows up among others. But if I try "Nijala" (missing n), only the correct animes show up:

![image](https://github.com/jikan-me/jikan-rest/assets/27897747/385daf93-e9ea-460a-9ebd-84a05e280fdf)

**Comment by pushrbx** [comment]
@Prid13 which one should be the first hit? [Ninjala TV](https://myanimelist.net/anime/50418/Ninjala) or the [Ninjala ONA](https://myanimelist.net/anime/42658/Ninjala)?

**Comment by Prid13** [comment]
@pushrbx personally I would expect [Ninjala TV](https://myanimelist.net/anime/50418/Ninjala) since it's a full-fledged anime with 20-minute episodes and ongoing with 70+ episodes, while the [ONA](https://myanimelist.net/anime/42658/Ninjala) was a promo tie-in for [the game of the same name](https://en.wikipedia.org/wiki/Ninjala) (despite airing first).

But honestly it doesn't really matter which is first. The main issue was _not_ getting any relevant searches when searching for "Ninjala" 😅

**Comment by pushrbx** [comment]
> @pushrbx personally I would expect [Ninjala TV](https://myanimelist.net/anime/50418/Ninjala) since it's a full-fledged anime with 20-minute episodes and ongoing with 70+ episodes, while the [ONA](https://myanimelist.net/anime/42658/Ninjala) was a promo tie-in for [the game of the same name](https://en.wikipedia.org/wiki/Ninjala) (despite airing first).
> 
> 
> 
> But honestly it doesn't really matter which is first. The main issue was _not_ getting any relevant searches when searching for "Ninjala" 😅

I should have said that I fixed this issue on my end today and I wanted to have a more accurate acceptance criteria to sign this off.

**Comment by Prid13** [comment]
@pushrbx sorry, my bad 😅 Ninjala TV should be first in my personal opinion (I have not watched these animes).

**Comment by Prid13** [comment]
@pushrbx not sure if you've only fixed this one edge case or most edge cases with similar "issues", because I found another one. Try searching for "persona". Literally everything other than the Persona series show up 😅

Now, remove any one letter, like "prsona", and you get the correct results:

![image](https://github.com/jikan-me/jikan-rest/assets/27897747/ec520239-e83b-4e3c-abe1-bdf34d9fad83)

**Comment by pushrbx** [comment]
On my end with the fixes im working on: currently if I look for "Persona" it works as expected. However with "prsona" I get nothing, which is a bit odd... Because that means that the typo correction doesn't work with that term for some reason.

**Comment by pushrbx** [comment]
Somewhat fixed in #409 , however it's not yet deployed to prod.

**Comment by irfan-dahir** [comment]
Resolved

**Comment by Wamy-Dev** [comment]
can we please reopen? Search terms such as "Girls & Panzer" do not show up with the correct searching

**Comment by Prid13** [comment]
> However with "prsona" I get nothing, which is a bit odd... Because that means that the typo correction doesn't work with that term for some reason.

"prsona" still isn't working in the new version 😅

Thanks for all the hard work btw, immensely appreciate it ⭐

**Comment by pushrbx** [comment]
> > However with "prsona" I get nothing, which is a bit odd... Because that means that the typo correction doesn't work with that term for some reason.
> 
> "prsona" still isn't working in the new version sweat_smile otoh, "perona" works.
> 
> Thanks for all the hard work btw, immensely appreciate it star

`prsona` will not work, that's entirely a question for typesense dev team, I don't think we can fix it on our end until we understand how we can tune typesense for anime/manga titles. :smile_cat:
